name: 'Notify slack channel about new contributor'

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Is new-contributor welcome bot?
        id: checkNewContributor
        run: |
          expectedMessage='thanks for opening your first'
          if [[ "$COMMENT" == *"$expectedMessage"* ]]; then
            echo "::set-output name=isNewContributor::true"
          else
            echo "::set-output name=isNewContributor::false"
          fi
        env:
          COMMENT: ${{ github.event.comment.body }}
      - name: Send slack message
        if: steps.checkNewContributor.isNewContributor == 'true'
        run: |
          echo "This is from a new contributor"
